name: Cypress Tests

on:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run 🧪
        uses: cypress-io/github-action@v2
      - run: npm run report:merge
      - run: npm run report:mocha

      - name: Reports deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
            BRANCH: gh-pages
            FOLDER: mochawesome-report
            